export const pluralToKind = plural => {
  const convertKind = {
    secrets: 'Secret',
    namespaces: 'Namespace',
    servicebrokers: 'ServiceBroker',
    serviceclasses: 'ServiceClass',
    serviceplans: 'ServicePlan',
    clusterservicebrokers: 'ClusterServiceBroker',
    clusterserviceclasses: 'ClusterServiceClass',
    clusterserviceplans: 'ClusterServicePlan',
    serviceinstances: 'ServiceInstance',
    servicebindings: 'ServiceBinding',
    catalogserviceclaims: 'CatalogServiceClaim',
    templates: 'Template',
    templateinstances: 'TemplateInstance',
    namespaceclaims: 'NamespaceClaim',
    rolebindingclaims: 'RoleBindingClaim',
    resourcequotaclaims: 'ResourceQuotaClaim',
    tasks: 'Task',
    taskruns: 'TaskRun',
    pipelines: 'Pipeline',
    pipelineruns: 'PipelineRun',
    approvals: 'Approval',
    pipelineresources: 'PipelineResource',
    hyperclusterresources: 'HyperClusterResource',
    federatedconfigmaps: 'FederatedConfigMap',
    federateddeployments: 'FederatedDeployment',
    federatedingresses: 'FederatedIngress',
    federatedjobs: 'FederatedJob',
    federatednamespaces: 'FederatedNamespace',
    federatedreplicasets: 'FederatedReplicaSet',
    federatedsecrets: 'federatedsecret',
    federatedservices: 'FederatedService',
    federatedpods: 'FederatedPod',
    federatedhorizontalpodautoscalers: 'FederatedHorizontalPodAutoscaler',
    federateddaemonsets: 'FederatedDaemonSet',
    federatedstatefulsets: 'FederatedStatefulSet',
    federatedcronjobs: 'FederatedCronJob',
  };
  return convertKind[plural];
};

export const crd = ['namespaceclaims', 'rolebindingclaims', 'resourcequotaclaims'];
