export * from './add-page';
export * from './catalog-page';
export * from './container-image-page';
export * from './dev-file-page';
export * from './event-source-page';
export * from './git-page';
export * from './yaml-page';
export * from './channel-page';
export * from './dockerfile-page';
