export const chartAreaPO = {
  editApplicationGrouping: '[data-test-action="Edit application grouping"]',
  editPodCount: '[data-test-action="Edit Pod count"]',
  pauseRollouts: '[data-test-action="Pause rollouts"]',
  addHealthChecks: '[data-test-action="Add Health Checks"]',
  addHorizontalPod: '[data-test-action="Add HorizontalPodAutoscaler"]',
  addStorage: '[data-test-action="Add storage"]',
  editUpdateStrategy: '[data-test-action="Edit update strategy"]',
  editLabels: '[data-test-action="Edit labels"]',
  editAnnotations: '[data-test-action="Edit annotations"]',
  editDeployment: '[data-test-action="Edit Deployment"]',
  deleteDeployment: '[data-test-action="Delete Deployment"]',
  topologyArea: '[data-test-id="topology"]',
  addToProject: '.odc-topology-context-menu',
  samples: '[data-test-action="Samples"]',
  importFromGit: '[data-test-action="Import from Git"]',
  containerImage: '[data-test-action="Container Image"]',
  catalog: '[data-test-action="From Catalog"]',
  database: '[data-test-action="Database"]',
  operatorBacked: '[data-test-action="Operator Backed"]',
  helmCharts: '[data-test-action="Helm Charts"]',
  eventsource: '[data-test-action="Event Source"]',
  channel: '[data-test-action="Channel"]',
  filterItem: 'input[placeholder="Filter by keyword..."]',
  sampleGo: '[data-test="Sample-Go"]',
  submitButton: '[data-test-id="submit-button"]',
  deployImage: '[data-test-id="deploy-image-search-term"]',
  validationText: '#form-input-searchTerm-field-helper',
  pythonBuilderImage: '[data-test="BuilderImage-Python"]',
  overlayCreate: '.co-catalog-page__overlay-action',
  gitInputURL: '[data-test-id="git-form-input-url"]',
  postgresqlTemplate: '[data-test="Template-PostgreSQL"]',
  operatorBackedPostgres: '[data-test="OperatorBackedService-Postgres Cluster"]',
  operatorBackedRedis: '[data-test="OperatorBackedService-Redis"]',
  helmNodejs: '[data-test="HelmChart-Nodejs"]',
  helmReleaseName: '#form-input-releaseName-field',
  apiEventSource: '[data-test="EventSource-ApiServerSource"]',
  eventName: '[data-test="pairs-list-name"]',
  eventValue: '[data-test="pairs-list-value"]',
  channelName: '[data-test-id="channel-name"]',
  saveChanges: '[data-test="save-changes"]',
  yamlEditor: 'div.monaco-scrollable-element.editor-scrollable.vs-dark',
  yamlView: '[data-test="import-yaml"]',
  dangerAlert: '[aria-label="Danger Alert"]',
  infoAlert: '[aria-label="Info Alert"]',
  contentScrollable: '#content-scrollable',
  gitForm: '[data-test-id="import-git-form"]',
};
