export const hpaPO = {
  navWorkloads: '[data-quickstart-id="qs-nav-workloads"]',
  nav: '[data-test="nav"]',
  createItem: '[data-test="item-create"]',
  saveChanges: '[data-test="save-changes"]',
  resourceTitle: '[data-test-id="resource-title"]',
  hpaHeading: '[data-test-section-heading="HorizontalPodAutoscaler details"]',
  itemFilter: '[data-test-id="item-filter"]',
  resourceItem: '[class="co-resource-item"]',
  actionMenu: '[data-test-id="actions-menu-button"]',
  modalTitle: '[data-test-id="modal-title"]',
  deleteOption: '[data-test="confirm-action"]',
  exampleHPA: '[data-test-id="example"]',
  emptyMessage: '[data-test="empty-message"]',
  nameHPA: '[id="form-input-formData-metadata-name-field"]',
  minhpaPod: '[name="formData.spec.minReplicas"]',
  maxhpaPod: '[name="formData.spec.maxReplicas"]',
  cpu: '[id="cpu"]',
  memory: '[id="memory"]',
  submitBtn: '[data-test-id="submit-button"]',
  sectionHeading: '.sidebar__section-heading',
  sidebarClose: '[data-test-id="sidebar-close-button"]',
  switchToggler: '[data-test-id="topology-switcher-view"]',
  hpaFormName: '[name="formData.metadata.name"]',
  podRing: '[class="odc-pod-ring"]',
  nodeList: '[class="list-group-item container-fluid"]',
};
