apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: @@NAME_NS@@
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      hypercloud: ui
      app: console
  template:
    metadata:
      name: hypercloud-ui
      labels:
        hypercloud: ui
        app: console
    spec:
      serviceAccountName: @@NAME_NS@@-admin
      containers:
      - command:
        - /opt/bridge/bin/bridge
        - --public-dir=/opt/bridge/static
        - --listen=https://0.0.0.0:6443
        - --tls-cert-file=/var/https-cert/tls.crt
        - --tls-key-file=/var/https-cert/tls.key
        - --hypercloud-endpoint=http://@@HC4@@
        - --prometheus-endpoint=http://@@PROM@@/api
        - --grafana-endpoint=http://@@GRAFANA@@/
        - --kiali-endpoint=https://@@KIALI@@/api/kiali
        - --jaeger-endpoint=http://@@JAEGER@@/api/jaeger
        - --approval-endpoint=http://@@APPROVAL@@/approve
        - --kubeflow-endpoint=http://@@KUBEFLOW@@/
        - --vnc-endpoint=http://@@VNC@@/
        - --hyperauth-endpoint=https://@@HYPERAUTH@@/auth
        - --webhook-endpoint=https://@@WEBHOOK@@/api/webhook/
        - --keycloak-realm=@@REALM@@
        - --keycloak-auth-url=https://@@KEYCLOAK@@/auth
        - --keycloak-client-id=@@CLIENTID@@        
        - --hdc-mode=@@HDC_FLAG@@
        - --tmaxcloud-portal=@@PORTAL@@
        image: tmaxcloudck/hypercloud-console:@@VER@@
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/https-cert
          name: https-cert
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /etc/timezone
          name: timezone
          readOnly: true
        name: console
        ports:
        - containerPort: 6443
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: '2Gi'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: https-cert
        secret:
          defaultMode: 288
          secretName: console-https-secret
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: timezone
        hostPath:
          path: /etc/timezone
