apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: python
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: user-analytics
    app.kubernetes.io/version: "1.0"
spec:
  selector:
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: python
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: user-analytics
    app.kubernetes.io/version: "1.0"
  ports:
    - port: 80
