kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: catalogd-route
  namespace: openshift-catalogd
spec:
  to:
    kind: Service
    name: catalogd-service
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
