enableInlineBuilds: true

enableScripts: false

enableTelemetry: false

httpTimeout: 600000

nodeLinker: node-modules

npmMinimalAgeGate: 3d

httpRetry: 9

npmPreapprovedPackages:
  - "@openshift/*"
  - "@patternfly/*"

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - s390x
    - ppc64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.18.0.cjs
