enableInlineBuilds: true

enableScripts: false

enableTelemetry: false

httpTimeout: 600000

nodeLinker: node-modules

npmMinimalAgeGate: 3d

supportedArchitectures:
  os: ["linux", "darwin"]
  cpu: ["x64", "arm64", "s390x", "ppc64"]

yarnPath: .yarn/releases/yarn-4.12.0.cjs
