#!/bin/bash -e

# Compiles binaries and static assets using docker containers.

REPO=github.com/coreos-inc/bridge

echo "compiling go..."
docker run --rm -v `pwd`:/go/src/$REPO -w /go/src/$REPO quay.io/coreosinc/web-builder:latest ./build

echo "compiling javascript..."
docker run --rm -v `pwd`:/go/src/$REPO -w /go/src/$REPO quay.io/coreosinc/web-builder:latest ./build-web
