#!/bin/bash -e

# build frontend assets into ./frontend/public/dist
# requires reinstalling gulp-sass for platform-specific c bindings
cd frontend && npm install gulp-sass@1.3.3 && ./node_modules/.bin/gulp
