#!/bin/bash -e

# docker build, tag, and push a docker image to quay.io/coreos/tectonic-console

registry=quay.io
repo=$registry/coreos/tectonic-console

if [ -v $DOCKER_USER ] || [ -v $DOCKER_PASSWORD ]; then
    echo "env variables not set. skipping login, assuming creds in .dockercfg"
else
    echo logging in as $DOCKER_USER
    docker login --username="$DOCKER_USER" --password="$DOCKER_PASSWORD" --email="docker.login@coreos.com" $registry
fi

git_sha=$(git rev-parse HEAD)

docker build -q --rm=true -t $repo:$git_sha .
docker tag -f $repo:$git_sha $repo:latest
docker push $repo:$git_sha
docker push $repo:latest
