#!/bin/bash -e
#
# USAGE:
#
# With env vars:
#   MYVAR=foo OTHERVAR=bar DOCKER_ENV=MYVAR,OTHERVAR ./builder-run ./my-script --my-script-arg1 --my-script-arg2
#
# Without env vars:
#   ./builder-run ./my-script --my-script-arg1 --my-script-arg2


BUILDER_IMAGE=quay.io/coreos/tectonic-console-builder:v11

# forward whitelisted env variables to docker
ENV_STR=""
for VAR in ${DOCKER_ENV//,/ }; do
    ENV_STR="$ENV_STR -e $VAR=${!VAR}"
done

docker run $ENV_STR --rm --net=host \
       --user="${BUILDER_RUN_USER}" \
       -v "$(pwd)":/go/src/github.com/coreos-inc/bridge \
       -w /go/src/github.com/coreos-inc/bridge \
       $BUILDER_IMAGE "$@"
