#!/bin/bash -e

# build frontend assets into ./frontend/public/dist
# requires reinstalling gulp-sass for platform-specific c bindings

cd frontend;
rm -rf ./node_modules && true;
npm install && ./node_modules/.bin/gulp
