#!/bin/bash -e

[ -n "${COLLECTOR_DOCKER_REPO}" ] || {
	echo "COLLECTOR_DOCKER_REPO not set"
	exit 1
}

[ -n "${GENERATOR_DOCKER_REPO}" ] || {
	echo "GENERATOR_DOCKER_REPO not set"
	exit 1
}

[ -n "${DOCKER_TAG}" ] || {
	echo "DOCKER_TAG not set"
	exit 1
}

docker build --rm --file Dockerfile-collector --tag ${COLLECTOR_DOCKER_REPO}:${DOCKER_TAG} .
docker build --rm --file Dockerfile-generator --tag ${GENERATOR_DOCKER_REPO}:${DOCKER_TAG} .
