#!/bin/bash -e
#
# Run all tests
#   ./test
#   ./test -v
#
# Run tests for one package
#   PKG=./unit ./test
#   PKG=ssh ./test
#

# Invoke ./cover for HTML output
COVER=${COVER:-"-cover"}

TESTABLE="pkg/collector"
FORMATTABLE="$TESTABLE cmd/tectonic-stats-collector pkg/generator pkg/stats"

# user has not provided PKG override
if [ -z "$PKG" ]; then
	TEST=$TESTABLE
	FMT=$FORMATTABLE

# user has provided PKG override
else
	# strip out slashes and dots from PKG=./foo/
	TEST=${PKG//\//}
	TEST=${TEST//./}

	# only run gofmt on packages provided by user
	FMT="$TEST"
fi

# split TEST into an array and prepend repo path to each local package
split=(${TEST// / })
TEST=${split[@]/#/github.com/coreos-inc/tectonic-stats-collector/}

echo "Running tests..."

# TODO(philips) This is a for loop b/c postgres was getting unhappy about
# dropping tables and recreating from a single process AFAICT.
for i in ${TESTABLE}; do
	GOPATH=${GOPATH}:${PWD}/Godeps/_workspace go test ${COVER} ./${i}
done

echo "Checking gofmt..."
fmtRes=$(gofmt -l $FMT)
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Checking govet..."
vetRes=$(go vet $TEST)
if [ -n "${vetRes}" ]; then
	echo -e "govet checking failed:\n${vetRes}"
	exit 255
fi

echo "Success"
