export const pageTitle = {
  Git: 'Import from Git',
  ContainerImage: 'Deploy Image',
  DockerFile: 'Import from Dockerfile',
  YAML: 'Import YAML',
  DeveloperCatalog: 'Developer Catalog',
  Pipelines: 'Pipelines',
  EventSource: 'Event Sources',
  helmReleaseDetails: 'Helm Release Details',
  upgradeHelmRelease: 'Upgrade Helm Release',
  operatorHub: 'OperatorHub',
  Add: 'Add',
  GitOPs: 'GitOps',
  Monitoring: 'Monitoring',
  BuildConfigs: 'Build Configs',
  Search: 'Search',
  HelmReleases: 'Helm Releases',
  Project: 'Project Details',
  ConfigMaps: 'Config Maps',
  Secrets: 'Secrets',
  PipelineRunDetails: 'Pipeline Run details',
  PipelineDetails: 'Pipeline details',
  TriggerTemplateDetails: 'Trigger Template details',
  EventListenerDetails: 'EventListener details',
  ClusterTriggerTemplateDetails: 'ClusterTriggerBinding Details',
};
