export const pageTitle = {
  Git: 'Import from Git',
  ContainerImage: 'Deploy Image',
  DockerFile: 'Import from Dockerfile',
  YAML: 'Import YAML',
  DeveloperCatalog: 'Developer Catalog',
  DevFile: 'Import from Devfile',
  Pipelines: 'Pipelines',
  PipelineBuilder: 'Pipeline builder',
  EventSource: 'Event Sources',
  CreateEventSource: 'Create Event Source',
  upgradeHelmRelease: 'Upgrade Helm Release',
  Channel: 'Channel',
  Add: 'Add',
  GitOPs: 'GitOps',
  Monitoring: 'Monitoring',
  BuildConfigs: 'Build Configs',
  Search: 'Search',
  HelmReleases: 'Helm Releases',
  Project: 'Project Details',
  ConfigMaps: 'Config Maps',
  Secrets: 'Secrets',
  PipelineRunDetails: 'PipelineRun details',
  PipelineDetails: 'Pipeline details',
  TriggerTemplateDetails: 'TriggerTemplate details',
  EventListenerDetails: 'EventListener details',
  ClusterTriggerTemplateDetails: 'ClusterTriggerBinding details',
  Templates: 'Templates',
  BuilderImages: 'Builder Images',
  HelmCharts: 'Helm Charts',
  InstallHelmCharts: 'Install Helm Chart',
  OperatorBacked: 'Operator Backed',
  HelmReleaseDetails: 'Helm Release details',
  UpgradeHelmRelease: 'Upgrade Helm Release',
  OperatorHub: 'OperatorHub',
  AddHealthChecks: 'Add health checks',
  InstallOperator: 'Install Operator',
  InstalledOperators: 'Installed Operators',
  Environments: 'Environments',
  PipelineRuns: 'PipelineRuns',
  Eventing: 'Eventing',
  RedHatOpenShiftServerless: 'Red Hat OpenShift Serverless',
  CreateKnativeServing: 'Create KnativeServing',
  CreateKnativeEventing: 'Create KnativeEventing',
  UploadJarFile: 'Upload JAR file',
  KnativeServings: 'KnativeServings',
  KnativeEventings: 'KnativeEventings',
};
