export const pageTitle = {
  Git: 'Import from Git',
  ContainerImage: 'Deploy Image',
  DockerFile: 'Import from Dockerfile',
  YAML: 'Import YAML',
  DeveloperCatalog: 'Developer Catalog',
  DevFile: 'Import from Devfile',
  Pipelines: 'Pipelines',
  PipelineBuilder: 'Pipeline builder',
  EventSource: 'Event Sources',
  upgradeHelmRelease: 'Upgrade Helm Release',
  Add: 'Add',
  GitOPs: 'GitOps',
  Monitoring: 'Monitoring',
  BuildConfigs: 'Build Configs',
  Search: 'Search',
  HelmReleases: 'Helm Releases',
  Project: 'Project Details',
  ConfigMaps: 'Config Maps',
  Secrets: 'Secrets',
  PipelineRunDetails: 'Pipeline Run details',
  PipelineDetails: 'Pipeline details',
  TriggerTemplateDetails: 'Trigger Template details',
  EventListenerDetails: 'Event Listener details',
  ClusterTriggerTemplateDetails: 'ClusterTriggerBinding details',
  Templates: 'Templates',
  BuilderImages: 'Builder Images',
  HelmCharts: 'Helm Charts',
  InstallHelmCharts: 'Install Helm Chart',
  OperatorBacked: 'Operator Backed',
  HelmReleaseDetails: 'Helm Release details',
  UpgradeHelmRelease: 'Upgrade Helm Release',
  OperatorHub: 'OperatorHub',
  AddHealthChecks: 'Add health checks',
  InstallOperator: 'Install Operator',
  InstalledOperators: 'Installed Operators',
  Environments: 'Environments',
};
