export enum displayOptions {
  PodCount = 'Pod Count',
  Labels = 'Labels',
  ApplicationGroupings = 'Application Groupings',
  HelmReleases = 'Helm Releases',
  KnativeServices = 'Knative Services',
  ConnectivityMode = 'Connectivity',
  ConsumptionMode = 'Consumption',
}

export enum nodeActions {
  EditApplicationGrouping = 'Edit Application grouping',
  EditPodCount = 'Edit Pod count',
  PauseRollOuts = 'Pause rollouts',
  AddHealthChecks = 'Add Health Checks',
  AddHorizontalPodAutoScaler = 'Add HorizontalPodAutoscaler',
  AddStorage = 'Add storage',
  EditUpdateStrategy = 'Edit update strategy',
  EditLabels = 'Edit labels',
  EditDeployment = 'Edit Deployment',
  DeleteDeployment = 'Delete Deployment',
  EditAnnotations = 'Edit annotations',
  MoveSink = 'Move sink',
  EditSinkBinding = 'Edit SinkBinding',
  DeleteSinkBinding = 'Delete SinkBinding',
  DeleteService = 'Delete Service',
  EditService = 'Edit Service',
  EditHealthChecks = 'Edit Health Checks',
  HelmReleases = 'Helm Releases',
  SetTrafficDistribution = 'Set traffic distribution',
  AddSubscription = 'Add Subscription',
  EditInMemoryChannel = 'Edit InMemoryChannel',
  DeleteInMemoryChannel = 'Delete InMemoryChannel',
}
