export const LAST_PERSPECTIVE_USER_PREFERENCE_KEY = 'console.lastPerspective';
export const FAVORITES_USER_PREFERENCE_KEY = 'console.favorites';
export const HIDE_USER_WORKLOAD_NOTIFICATIONS_USER_PREFERENCE_KEY =
  'console.hideUserWorkloadNotifications';

export const FLAG_DEVELOPER_PERSPECTIVE = 'DEVELOPER_PERSPECTIVE';
export const FLAG_CAN_GET_CONSOLE_OPERATOR_CONFIG = 'CAN_GET_CONSOLE_OPERATOR_CONFIG';
export const FLAG_TECH_PREVIEW = 'TECH_PREVIEW';
export const FLAG_INTEGRATION_TEST = 'INTEGRATION_TEST';

export const ACM_PERSPECTIVE_ID = 'acm';
export const ADMIN_PERSPECTIVE_ID = 'admin';
