export const OBC_NAME = 'test-obc';
export const BOUND = 'Bound';
export const ATTACH_TO_DEPLOYMENT = 'Attach to Deployment';
export const OBC_RESOURCE_PATH = 'objectbucket.io~v1alpha1~ObjectBucketClaim';
export const OBC_STORAGE_CLASS = 'openshift-storage\\.noobaa\\.io';
export const OBC_STORAGE_CLASS_EXACT = 'openshift-storage.noobaa.io';
export const MASKED_VALUE = 'Value hidden\n•••••';
export const NOOBAA_LABEL = 'app\n=\nnoobaa';
export const NO_ANNOTATIONS = '0 Annotations';
export const ACCESS_KEY = '[a-zA-Z0-9]{20}';
export const SECRET_KEY = '[a-zA-Z0-9/+]{40}';
export const MOCK_SECRET = 'test-secret-for-bs';
export const RGW_PROVISIONER = 'openshift-storage.ceph.rook.io/bucket';
