apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: simple-pipeline-1
spec:
  pipelineRef:
    name: simple-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: skaffold-git
    - name: web-image
      resourceRef:
        name: skaffold-image-leeroy-web
  trigger:
      type: manual
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: mapit-deploy-pipelinerun-4
spec:
  serviceAccount: pipeline
  pipelineRef:
    name: mapit-deploy-pipeline
  trigger:
    type: manual
  resources:
  - name: mapit-git
    resourceRef:
      name: mapit-git
  - name: mapit-image
    resourceRef:
      name: mapit-image