apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consolenotifications.console.openshift.io
  annotations:
    displayName: ConsoleNotification
    description: Extension for configuring openshift web console notifications.
spec:
  group: console.openshift.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Cluster
  names:
    plural: consolenotifications
    singular: consolenotification
    kind: ConsoleNotification
    listKind: ConsoleNotificationList
  additionalPrinterColumns:
  - name: Text
    type: string
    JSONPath: .spec.notification.text
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Represents console notification spec
          required:
          - notification
          properties:
            notification:
              type: object
              description: Object that holds notification extension
              required:
                - text
                - position
              properties:
                text:
                  type: string
                  description: Text of the notification
                position:
                  type: string
                  description: The location of the notification (top, bottom, topBottom)
                  pattern: '\btop\b|\bbottom\b|\btopBottom\b'
                link:
                  type: object
                  description: Object that holds notification link details
                  required:
                    - href
                  properties:
                    text:
                      type: string
                      description: Text of the link
                    href:
                      type: string
                      description: Absolute URL for the link
                      pattern: '^((https?):\/\/)?(www.)?[a-z0-9]+\.[a-z]+(\/[a-zA-Z0-9#]+\/?)*$'
                    opensNewWindow:
                      type: boolean
                      description: Determines whether the link opens in a new window
                backgroundColor:
                  type: string
                  description: The background color for the notification
                color:
                  type: string
                  description: The color of the text for the notification
