apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consolenotifications.console.openshift.io
  annotations:
    displayName: ConsoleNotification
    description: Extension for configuring openshift web console notifications.
spec:
  group: console.openshift.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Cluster
  names:
    plural: consolenotifications
    singular: consolenotification
    kind: ConsoleNotification
    listKind: ConsoleNotificationList
  additionalPrinterColumns:
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Represents console notification spec
          required:
          - notification
          properties:
            notification:
              type: object
              description: Object that holds notification extension
              required:
                - text
              properties:
                text:
                  type: string
                  description: Text of the notification
                link:
                  type: object
                  description: Object that holds notification link details
                  required:
                    - href
                  properties:
                    href:
                      type: string
                      description: HREF for the link
                    text:
                      type: string
                      description: Text of the link
