apiVersion: v1
kind: Namespace
metadata:
  name: console-system

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: console-system-quota
  namespace: console-system
spec:
  hard:
    limits.cpu: "2"
    limits.memory: "5Gi"
    requests.storage: "10Gi"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-system-admin
  namespace: console-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-system-admin
  namespace: console-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
  
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-system-admin
subjects:
  - kind: ServiceAccount
    name: console-system-admin
    namespace: console-system
roleRef:
  kind: ClusterRole
  name: console-system-admin
  apiGroup: rbac.authorization.k8s.io