apiVersion: v1
kind: BuildConfig
metadata:
  name: wit-build
  labels: 
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: wit
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "v1.0.0"
spec:
  source:
    git:
      uri: "git@github.com:DhritiShikhar/topology-example.git"
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: wit-build:latest
