export const POD_STATUS_NOT_SCHEDULABLE = 'POD_NOT_SCHEDULABLE';
export const POD_STATUS_CONTAINER_FAILING = 'POD_CONTAINER_FAILING';
export const POD_STATUS_NOT_READY = 'POD_NOT_READY';

export const POD_STATUS_FAILED = 'POD_FAILED';
export const POD_STATUS_CRASHLOOP_BACKOFF = 'POD_CRASHLOOP_BACKOFF';
export const POD_STATUS_UNKNOWN = 'POD_STATUS_UNKNOWN';

export const POD_STATUS_PENDING = 'POD_STATUS_PENDING';
export const POD_STATUS_COMPLETED = 'POD_STATUS_COMPLETED';
export const POD_STATUS_SUCCEEDED = 'POD_STATUS_SUCCEEDED';
export const POD_STATUS_RUNNING = 'POD_STATUS_RUNNING';
