// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DataVolumeSourceHTTP provides the parameters to create a Data Volume from an HTTP source
 * @export
 * @interface V1alpha1DataVolumeSourceHTTP
 */
export interface V1alpha1DataVolumeSourceHTTP {
  /**
   * CertConfigMap provides a reference to the Registry certs
   * @type {string}
   * @memberof V1alpha1DataVolumeSourceHTTP
   */
  certConfigMap?: string;
  /**
   * SecretRef provides the secret reference needed to access the HTTP source
   * @type {string}
   * @memberof V1alpha1DataVolumeSourceHTTP
   */
  secretRef?: string;
  /**
   * URL is the URL of the http source
   * @type {string}
   * @memberof V1alpha1DataVolumeSourceHTTP
   */
  url?: string;
}
