// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DataVolumeStatus provides the parameters to store the phase of the Data Volume
 * @export
 * @interface V1alpha1DataVolumeStatus
 */
export interface V1alpha1DataVolumeStatus {
  /**
   * Phase is the current phase of the data volume
   * @type {string}
   * @memberof V1alpha1DataVolumeStatus
   */
  phase?: string;
  /**
   *
   * @type {string}
   * @memberof V1alpha1DataVolumeStatus
   */
  progress?: string;
}
