// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1LocalObjectReference } from './V1LocalObjectReference';

/**
 * Represents a cloud-init config drive user data source. More info: https://cloudinit.readthedocs.io/en/latest/topics/datasources/configdrive.html
 * @export
 * @interface V1CloudInitConfigDriveSource
 */
export interface V1CloudInitConfigDriveSource {
  /**
   * NetworkData contains config drive inline cloud-init networkdata. + optional
   * @type {string}
   * @memberof V1CloudInitConfigDriveSource
   */
  networkData?: string;
  /**
   * NetworkDataBase64 contains config drive cloud-init networkdata as a base64 encoded string. + optional
   * @type {string}
   * @memberof V1CloudInitConfigDriveSource
   */
  networkDataBase64?: string;
  /**
   *
   * @type {V1LocalObjectReference}
   * @memberof V1CloudInitConfigDriveSource
   */
  networkDataSecretRef?: V1LocalObjectReference;
  /**
   *
   * @type {V1LocalObjectReference}
   * @memberof V1CloudInitConfigDriveSource
   */
  secretRef?: V1LocalObjectReference;
  /**
   * UserData contains config drive inline cloud-init userdata. + optional
   * @type {string}
   * @memberof V1CloudInitConfigDriveSource
   */
  userData?: string;
  /**
   * UserDataBase64 contains config drive cloud-init userdata as a base64 encoded string. + optional
   * @type {string}
   * @memberof V1CloudInitConfigDriveSource
   */
  userDataBase64?: string;
}
