// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * EmptyDisk represents a temporary disk which shares the vmis lifecycle.
 * @export
 * @interface V1EmptyDiskSource
 */
export interface V1EmptyDiskSource {
  /**
   * Capacity of the sparse disk.
   * @type {string}
   * @memberof V1EmptyDiskSource
   */
  capacity: string;
}
