// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a disk created on the cluster level
 * @export
 * @interface V1HostDisk
 */
export interface V1HostDisk {
  /**
   * Capacity of the sparse disk +optional
   * @type {string}
   * @memberof V1HostDisk
   */
  capacity?: string;
  /**
   * The path to HostDisk image located on the cluster
   * @type {string}
   * @memberof V1HostDisk
   */
  path: string;
  /**
   * Shared indicate whether the path is shared between nodes
   * @type {boolean}
   * @memberof V1HostDisk
   */
  shared?: boolean;
  /**
   * Contains information if disk.img exists or should be created allowed options are \'Disk\' and \'DiskOrCreate\'
   * @type {string}
   * @memberof V1HostDisk
   */
  type: string;
}
