// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Initializer is information about an initializer that has not yet completed.
 * @export
 * @interface V1Initializer
 */
export interface V1Initializer {
  /**
   * name of the process that is responsible for initializing this object.
   * @type {string}
   * @memberof V1Initializer
   */
  name: string;
}
