// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1LunTarget
 */
export interface V1LunTarget {
  /**
   * Bus indicates the type of disk device to emulate. supported values: virtio, sata, scsi.
   * @type {string}
   * @memberof V1LunTarget
   */
  bus?: string;
  /**
   * ReadOnly. Defaults to false.
   * @type {boolean}
   * @memberof V1LunTarget
   */
  readonly?: boolean;
}
