export const addHealthChecksPO = {
  readinessProbe: {
    requestType: '#form-dropdown-healthChecks-readinessProbe-data-requestType-field',
    httpHeaderName: 'input[placeholder="header name"]',
    httpHeaderValue: 'input[placeholder="value"]',
    path: '#form-input-healthChecks-readinessProbe-data-httpGet-path-field',
    port: '#form-input-healthChecks-readinessProbe-data-httpGet-port-field',
    failureThreshold: '#form-input-healthChecks-readinessProbe-data-failureThreshold-field',
    successThreshold: '#form-input-healthChecks-readinessProbe-data-successThreshold-field',
    initialDelay: '#form-input-healthChecks-readinessProbe-data-initialDelaySeconds-field',
    period: '#form-input-healthChecks-readinessProbe-data-periodSeconds-field',
    timeout: '#form-input-healthChecks-readinessProbe-data-timeoutSeconds-field',
  },
  livenessProbe: {
    requestType: '#form-dropdown-healthChecks-livenessProbe-data-requestType-field',
    httpHeaderName: 'input[placeholder="header name"]',
    httpHeaderValue: 'input[placeholder="value"]',
    path: '#form-input-healthChecks-livenessProbe-data-httpGet-path-field',
    port: '#form-input-healthChecks-livenessProbe-data-httpGet-port-field',
    failureThreshold: '#form-input-healthChecks-livenessProbe-data-failureThreshold-field',
    successThreshold: '#form-input-healthChecks-livenessProbe-data-successThreshold-field',
    initialDelay: '#form-input-healthChecks-livenessProbe-data-initialDelaySeconds-field',
    period: '#form-input-healthChecks-livenessProbe-data-periodSeconds-field',
    timeout: '#form-input-healthChecks-livenessProbe-data-timeoutSeconds-field',
  },
  startupProbe: {
    requestType: '#form-dropdown-healthChecks-startupProbe-data-requestType-field',
    httpHeaderName: 'input[placeholder="header name"]',
    httpHeaderValue: 'input[placeholder="value"]',
    path: '#form-input-healthChecks-startupProbe-data-httpGet-path-field',
    port: '#form-input-healthChecks-startupProbe-data-httpGet-port-field',
    failureThreshold: '#form-input-healthChecks-startupProbe-data-failureThreshold-field',
    successThreshold: '#form-input-healthChecks-startupProbe-data-successThreshold-field',
    initialDelay: '#form-input-healthChecks-startupProbe-data-initialDelaySeconds-field',
    period: '#form-input-healthChecks-startupProbe-data-periodSeconds-field',
    timeout: '#form-input-healthChecks-startupProbe-data-timeoutSeconds-field',
  },
  add: '[data-test-id="submit-button"]',
  cancel: '[data-test-id="reset-button"]',
  save: '[data-test-id="submit-button"]',
  healthChecksForm: 'div.odc-heath-check-probe-form',
  successText: 'span.odc-heath-check-probe__successText',
  removeReadinessProbeIcon: '',
  readinessProbeAdded: '',
  livenessProbeAdded: '',
  addStartUpProbeAdded: '',
};
