---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedkafkarequests.rhoas.redhat.com
spec:
  group: rhoas.redhat.com
  names:
    kind: ManagedKafkaRequest
    plural: managedkafkarequests
    shortNames:
    - mkr
    singular: managedkafkarequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        managedKafkaRequestSpec:
          properties:
            accessTokenSecretName:
              type: string
          type: object
        status:
          properties:
            lastUpdate:
              type: string
            userKafkas:
              items:
                Schema:
                  properties:
                    mykafka1:
                      type: object
                    id:
                      type: string
                    created:
                      type: string
                    provider:
                      type: string
                    region:
                      type: string
                    owner:
                      type: string
                  type: object
              type: array
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
