export { ConfigMapsPage, ConfigMapsDetailsPage } from './configmap';
export { ContainersDetailsPage } from './container';
export { DaemonSetsPage, DaemonSetsDetailsPage } from './daemonset';
export { DeploymentsPage, DeploymentsDetailsPage } from './deployment';
export { JobsPage, JobsDetailsPage } from './job';
export { NamespacesPage, NamespacesDetailsPage } from './namespace';
export { NetworkPoliciesList, NetworkPoliciesPage, NetworkPoliciesDetailsPage } from './network-policy';
export { NodesPage, NodesDetailsPage } from './node';
export { PodsPage, PodsDetailsPage } from './pod';
export { ReplicaSetsPage, ReplicaSetsDetailsPage } from './replicaset';
export { ReplicationControllersPage, ReplicationControllersDetailsPage } from './replication-controller';
export { SecretsPage, SecretsDetailsPage } from './secret';
export { ServiceAccountsPage, ServiceAccountsDetailsPage } from './service-account';
export { ServicesPage, ServicesDetailsPage } from './service';
export { IngressesPage, IngressesDetailsPage } from './ingress';
export { ClusterRolesDetailsPage, RolesPage, RolesDetailsPage } from './RBAC/role';
export { RoleBindingsPage } from './RBAC/bindings';
export { EtcdClustersPage as etcdClustersPage, EtcdClustersDetailsPage as etcdClustersDetailsPage } from './etcd-cluster';
