const KUBE_DOCS = 'https://kubernetes.io/docs/concepts/storage/storage-classes';
export const AWS_EBS = () => `${KUBE_DOCS}/#aws-ebs`;
export const AZURE_DISK = () => `${KUBE_DOCS}/#azure-disk`;
export const AZURE_FILE = () => `${KUBE_DOCS}/#azure-file`;
export const GCE = () => `${KUBE_DOCS}/#gce`;
export const GLUSTERFS = () => `${KUBE_DOCS}/#glusterfs`;
export const LOCAL = () => `${KUBE_DOCS}/#local`;
export const OPENSTACK_CINDER = () => `${KUBE_DOCS}/#openstack-cinder`;
export const PORTWORX_VOLUME = () => `${KUBE_DOCS}/#portworx-volume`;
export const QUOBYTE = () => `${KUBE_DOCS}/#quobyte`;
export const SCALEIO = () => `${KUBE_DOCS}/#scaleio`;
export const STORAGEOS = () => `${KUBE_DOCS}/#storageos`;
export const VSPHERE = () => `${KUBE_DOCS}/#vsphere`;
