export enum CapacityQuery {
  MEMORY_TOTAL = 'MEMORY_TOTAL',
  MEMORY_USED = 'MEMORY_USED',
  NETWORK_TOTAL = 'NETWORK_TOTAL',
  NETWORK_USED = 'NETWORK_USED',
  CPU_USED = 'CPU_USED',
  STORAGE_USED = 'STORAGE_USED',
  STORAGE_TOTAL = 'STORAGE_TOTAL',
}
