import { FormikProps, FormikValues } from 'formik';

export const formikFormProps: FormikProps<FormikValues> = {
  values: {},
  initialValues: {},
  errors: {},
  touched: {},
  isSubmitting: true,
  isValidating: true,
  status: {},
  submitCount: 0,
  dirty: false,
  handleReset: jest.fn(),
  handleSubmit: jest.fn(),
  getFieldProps: jest.fn(),
  handleBlur: jest.fn(),
  handleChange: jest.fn(),
  initialErrors: {},
  initialStatus: {},
  initialTouched: {},
  isValid: true,
  registerField: jest.fn(),
  resetForm: jest.fn(),
  setErrors: jest.fn(),
  setFieldError: jest.fn(),
  setFieldTouched: jest.fn(),
  setFieldValue: jest.fn(),
  setFormikState: jest.fn(),
  setStatus: jest.fn(),
  setSubmitting: jest.fn(),
  setTouched: jest.fn(),
  setValues: jest.fn(),
  submitForm: jest.fn(),
  unregisterField: jest.fn(),
  validateField: jest.fn(),
  validateForm: jest.fn(),
  getFieldMeta: jest.fn(),
  validateOnBlur: true,
  validateOnChange: true,
};
