// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1NodeAffinity } from './V1NodeAffinity';
import { V1PodAffinity } from './V1PodAffinity';
import { V1PodAntiAffinity } from './V1PodAntiAffinity';

/**
 * Affinity is a group of affinity scheduling rules.
 * @export
 * @interface V1Affinity
 */
export interface V1Affinity {
  /**
   *
   * @type {V1NodeAffinity}
   * @memberof V1Affinity
   */
  nodeAffinity?: V1NodeAffinity;
  /**
   *
   * @type {V1PodAffinity}
   * @memberof V1Affinity
   */
  podAffinity?: V1PodAffinity;
  /**
   *
   * @type {V1PodAntiAffinity}
   * @memberof V1Affinity
   */
  podAntiAffinity?: V1PodAntiAffinity;
}
