// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DataVolumeSourceS3 provides the parameters to create a Data Volume from an S3 source
 * @export
 * @interface V1alpha1DataVolumeSourceS3
 */
export interface V1alpha1DataVolumeSourceS3 {
  /**
   * SecretRef provides the secret reference needed to access the S3 source
   * @type {string}
   * @memberof V1alpha1DataVolumeSourceS3
   */
  secretRef?: string;
  /**
   * URL is the url of the S3 source
   * @type {string}
   * @memberof V1alpha1DataVolumeSourceS3
   */
  url?: string;
}
