// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1APIGroup } from './V1APIGroup';

/**
 * APIGroupList is a list of APIGroup, to allow clients to discover the API at /apis.
 * @export
 * @interface V1APIGroupList
 */
export interface V1APIGroupList {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @type {string}
   * @memberof V1APIGroupList
   */
  apiVersion?: string;
  /**
   * groups is a list of APIGroup.
   * @type {Array<V1APIGroup>}
   * @memberof V1APIGroupList
   */
  groups: V1APIGroup[];
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1APIGroupList
   */
  kind?: string;
}
