// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * APIResource specifies the name of a resource and whether it is namespaced.
 * @export
 * @interface V1APIResource
 */
export interface V1APIResource {
  /**
   * categories is a list of the grouped resources this resource belongs to (e.g. \'all\')
   * @type {Array<string>}
   * @memberof V1APIResource
   */
  categories?: string[];
  /**
   * group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale\".
   * @type {string}
   * @memberof V1APIResource
   */
  group?: string;
  /**
   * kind is the kind for the resource (e.g. \'Foo\' is the kind for a resource \'foo\')
   * @type {string}
   * @memberof V1APIResource
   */
  kind: string;
  /**
   * name is the plural name of the resource.
   * @type {string}
   * @memberof V1APIResource
   */
  name: string;
  /**
   * namespaced indicates if a resource is namespaced or not.
   * @type {boolean}
   * @memberof V1APIResource
   */
  namespaced: boolean;
  /**
   * shortNames is a list of suggested short names of the resource.
   * @type {Array<string>}
   * @memberof V1APIResource
   */
  shortNames?: string[];
  /**
   * singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface.
   * @type {string}
   * @memberof V1APIResource
   */
  singularName: string;
  /**
   * verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy)
   * @type {Array<string>}
   * @memberof V1APIResource
   */
  verbs: string[];
  /**
   * version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource\'s group)\".
   * @type {string}
   * @memberof V1APIResource
   */
  version?: string;
}
