// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the firmware blob used to assist in the domain creation process. Used for setting the QEMU BIOS file path for the libvirt domain.
 * @export
 * @interface V1Bootloader
 */
export interface V1Bootloader {
  /**
   * If set (default), BIOS will be used.
   * @type {object}
   * @memberof V1Bootloader
   */
  bios?: object;
  /**
   * If set, EFI will be used instead of BIOS.
   * @type {object}
   * @memberof V1Bootloader
   */
  efi?: object;
}
