// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * UTC sets the guest clock to UTC on each boot.
 * @export
 * @interface V1ClockOffsetUTC
 */
export interface V1ClockOffsetUTC {
  /**
   * OffsetSeconds specifies an offset in seconds, relative to UTC. If set, guest changes to the clock will be kept during reboots and not reset.
   * @type {number}
   * @memberof V1ClockOffsetUTC
   */
  offsetSeconds?: number;
}
