// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1CPUFeature } from './V1CPUFeature';

/**
 * CPU allows specifying the CPU topology.
 * @export
 * @interface V1CPU
 */
export interface V1CPU {
  /**
   * Cores specifies the number of cores inside the vmi. Must be a value greater or equal 1.
   * @type {number}
   * @memberof V1CPU
   */
  cores?: number;
  /**
   * DedicatedCPUPlacement requests the scheduler to place the VirtualMachineInstance on a node with enough dedicated pCPUs and pin the vCPUs to it. +optional
   * @type {boolean}
   * @memberof V1CPU
   */
  dedicatedCpuPlacement?: boolean;
  /**
   * Features specifies the CPU features list inside the VMI. +optional
   * @type {Array<V1CPUFeature>}
   * @memberof V1CPU
   */
  features?: V1CPUFeature[];
  /**
   * Model specifies the CPU model inside the VMI. List of available models https://github.com/libvirt/libvirt/tree/master/src/cpu_map. It is possible to specify special cases like \"host-passthrough\" to get the same CPU as the node and \"host-model\" to get CPU closest to the node one. Defaults to host-model. +optional
   * @type {string}
   * @memberof V1CPU
   */
  model?: string;
  /**
   * Sockets specifies the number of sockets inside the vmi. Must be a value greater or equal 1.
   * @type {number}
   * @memberof V1CPU
   */
  sockets?: number;
  /**
   * Threads specifies the number of threads inside the vmi. Must be a value greater or equal 1.
   * @type {number}
   * @memberof V1CPU
   */
  threads?: number;
}
