// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DHCPExtraOptions defines Extra DHCP options for a VM.
 * @export
 * @interface V1DHCPPrivateOptions
 */
export interface V1DHCPPrivateOptions {
  /**
   * Option is an Integer value from 224-254 Required.
   * @type {number}
   * @memberof V1DHCPPrivateOptions
   */
  option: number;
  /**
   * Value is a String value for the Option provided Required.
   * @type {string}
   * @memberof V1DHCPPrivateOptions
   */
  value: string;
}
