// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1DHCPPrivateOptions } from './V1DHCPPrivateOptions';

/**
 * Extra DHCP options to use in the interface.
 * @export
 * @interface V1DHCPOptions
 */
export interface V1DHCPOptions {
  /**
   * If specified will pass option 67 to interface\'s DHCP server +optional
   * @type {string}
   * @memberof V1DHCPOptions
   */
  bootFileName?: string;
  /**
   * If specified will pass the configured NTP server to the VM via DHCP option 042. +optional
   * @type {Array<string>}
   * @memberof V1DHCPOptions
   */
  ntpServers?: string[];
  /**
   * If specified will pass extra DHCP options for private use, range: 224-254 +optional
   * @type {Array<V1DHCPPrivateOptions>}
   * @memberof V1DHCPOptions
   */
  privateOptions?: V1DHCPPrivateOptions[];
  /**
   * If specified will pass option 66 to interface\'s DHCP server +optional
   * @type {string}
   * @memberof V1DHCPOptions
   */
  tftpServerName?: string;
}
