// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1CPU } from './V1CPU';
import { V1Clock } from './V1Clock';
import { V1Devices } from './V1Devices';
import { V1Features } from './V1Features';
import { V1Firmware } from './V1Firmware';
import { V1Machine } from './V1Machine';
import { V1Memory } from './V1Memory';
import { V1ResourceRequirements } from './V1ResourceRequirements';

/**
 *
 * @export
 * @interface V1DomainSpec
 */
export interface V1DomainSpec {
  /**
   *
   * @type {V1Clock}
   * @memberof V1DomainSpec
   */
  clock?: V1Clock;
  /**
   *
   * @type {V1CPU}
   * @memberof V1DomainSpec
   */
  cpu?: V1CPU;
  /**
   *
   * @type {V1Devices}
   * @memberof V1DomainSpec
   */
  devices: V1Devices;
  /**
   *
   * @type {V1Features}
   * @memberof V1DomainSpec
   */
  features?: V1Features;
  /**
   *
   * @type {V1Firmware}
   * @memberof V1DomainSpec
   */
  firmware?: V1Firmware;
  /**
   *
   * @type {object}
   * @memberof V1DomainSpec
   */
  ioThreadsPolicy?: object;
  /**
   *
   * @type {V1Machine}
   * @memberof V1DomainSpec
   */
  machine?: V1Machine;
  /**
   *
   * @type {V1Memory}
   * @memberof V1DomainSpec
   */
  memory?: V1Memory;
  /**
   *
   * @type {V1ResourceRequirements}
   * @memberof V1DomainSpec
   */
  resources?: V1ResourceRequirements;
}
