// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1FeatureSpinlocks
 */
export interface V1FeatureSpinlocks {
  /**
   * Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true. +optional
   * @type {boolean}
   * @memberof V1FeatureSpinlocks
   */
  enabled?: boolean;
  /**
   * Retries indicates the number of retries. Must be a value greater or equal 4096. Defaults to 4096. +optional
   * @type {number}
   * @memberof V1FeatureSpinlocks
   */
  spinlocks?: number;
}
