// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1FeatureVendorID
 */
export interface V1FeatureVendorID {
  /**
   * Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true. +optional
   * @type {boolean}
   * @memberof V1FeatureVendorID
   */
  enabled?: boolean;
  /**
   * VendorID sets the hypervisor vendor id, visible to the vmi. String up to twelve characters.
   * @type {string}
   * @memberof V1FeatureVendorID
   */
  vendorid?: string;
}
