// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the genie cni network.
 * @export
 * @interface V1GenieNetwork
 */
export interface V1GenieNetwork {
  /**
   * References the CNI plugin name.
   * @type {string}
   * @memberof V1GenieNetwork
   */
  networkName: string;
}
