// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1HPETTimer
 */
export interface V1HPETTimer {
  /**
   * Enabled set to false makes sure that the machine type or a preset can\'t add the timer. Defaults to true. +optional
   * @type {boolean}
   * @memberof V1HPETTimer
   */
  present?: boolean;
  /**
   * TickPolicy determines what happens when QEMU misses a deadline for injecting a tick to the guest. One of \"delay\", \"catchup\", \"merge\", \"discard\".
   * @type {string}
   * @memberof V1HPETTimer
   */
  tickPolicy?: string;
}
