// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 * @export
 * @interface V1HTTPHeader
 */
export interface V1HTTPHeader {
  /**
   * The header field name
   * @type {string}
   * @memberof V1HTTPHeader
   */
  name: string;
  /**
   * The header field value
   * @type {string}
   * @memberof V1HTTPHeader
   */
  value: string;
}
