// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1DHCPOptions } from './V1DHCPOptions';
import { V1Port } from './V1Port';

/**
 *
 * @export
 * @interface V1Interface
 */
export interface V1Interface {
  /**
   * BootOrder is an integer value > 0, used to determine ordering of boot devices. Lower values take precedence. Each interface or disk that has a boot order must have a unique value. Interfaces without a boot order are not tried. +optional
   * @type {number}
   * @memberof V1Interface
   */
  bootOrder?: number;
  /**
   *
   * @type {object}
   * @memberof V1Interface
   */
  bridge?: object;
  /**
   *
   * @type {V1DHCPOptions}
   * @memberof V1Interface
   */
  dhcpOptions?: V1DHCPOptions;
  /**
   * Interface MAC address. For example: de:ad:00:00:be:af or DE-AD-00-00-BE-AF.
   * @type {string}
   * @memberof V1Interface
   */
  macAddress?: string;
  /**
   *
   * @type {object}
   * @memberof V1Interface
   */
  masquerade?: object;
  /**
   * Interface model. One of: e1000, e1000e, ne2k_pci, pcnet, rtl8139, virtio. Defaults to virtio.
   * @type {string}
   * @memberof V1Interface
   */
  model?: string;
  /**
   * Logical name of the interface as well as a reference to the associated networks. Must match the Name of a Network.
   * @type {string}
   * @memberof V1Interface
   */
  name: string;
  /**
   * If specified, the virtual network interface will be placed on the guests pci address with the specifed PCI address. For example: 0000:81:01.10 +optional
   * @type {string}
   * @memberof V1Interface
   */
  pciAddress?: string;
  /**
   * List of ports to be forwarded to the virtual machine.
   * @type {Array<V1Port>}
   * @memberof V1Interface
   */
  ports?: V1Port[];
  /**
   *
   * @type {object}
   * @memberof V1Interface
   */
  slirp?: object;
  /**
   *
   * @type {object}
   * @memberof V1Interface
   */
  sriov?: object;
}
