// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1Machine
 */
export interface V1Machine {
  /**
   * QEMU machine type is the actual chipset of the VirtualMachineInstance.
   * @type {string}
   * @memberof V1Machine
   */
  type: string;
}
