// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Hugepages } from './V1Hugepages';

/**
 * Memory allows specifying the VirtualMachineInstance memory features.
 * @export
 * @interface V1Memory
 */
export interface V1Memory {
  /**
   * Guest allows to specifying the amount of memory which is visible inside the Guest OS. The Guest must lie between Requests and Limits from the resources section. Defaults to the requested memory in the resources section if not specified. + optional
   * @type {string}
   * @memberof V1Memory
   */
  guest?: string;
  /**
   *
   * @type {V1Hugepages}
   * @memberof V1Memory
   */
  hugepages?: V1Hugepages;
}
