// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the multus cni network.
 * @export
 * @interface V1MultusNetwork
 */
export interface V1MultusNetwork {
  /**
   * Select the default network and add it to the multus-cni.io/default-network annotation.
   * @type {boolean}
   * @memberof V1MultusNetwork
   */
  _default?: boolean;
  /**
   * References to a NetworkAttachmentDefinition CRD object. Format: <networkName>, <namespace>/<networkName>. If namespace is not specified, VMI namespace is assumed.
   * @type {string}
   * @memberof V1MultusNetwork
   */
  networkName: string;
}
