// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1NodeSelector } from './V1NodeSelector';
import { V1PreferredSchedulingTerm } from './V1PreferredSchedulingTerm';

/**
 * Node affinity is a group of node affinity scheduling rules.
 * @export
 * @interface V1NodeAffinity
 */
export interface V1NodeAffinity {
  /**
   * The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding \"weight\" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.
   * @type {Array<V1PreferredSchedulingTerm>}
   * @memberof V1NodeAffinity
   */
  preferredDuringSchedulingIgnoredDuringExecution?: V1PreferredSchedulingTerm[];
  /**
   *
   * @type {V1NodeSelector}
   * @memberof V1NodeAffinity
   */
  requiredDuringSchedulingIgnoredDuringExecution?: V1NodeSelector;
}
