// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1NodeSelectorTerm } from './V1NodeSelectorTerm';

/**
 * A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
 * @export
 * @interface V1NodeSelector
 */
export interface V1NodeSelector {
  /**
   * Required. A list of node selector terms. The terms are ORed.
   * @type {Array<V1NodeSelectorTerm>}
   * @memberof V1NodeSelector
   */
  nodeSelectorTerms: V1NodeSelectorTerm[];
}
