// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PodDNSConfigOption defines DNS resolver options of a pod.
 * @export
 * @interface V1PodDNSConfigOption
 */
export interface V1PodDNSConfigOption {
  /**
   * Required.
   * @type {string}
   * @memberof V1PodDNSConfigOption
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof V1PodDNSConfigOption
   */
  value?: string;
}
