// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Port repesents a port to expose from the virtual machine. Default protocol TCP. The port field is mandatory
 * @export
 * @interface V1Port
 */
export interface V1Port {
  /**
   * If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services. +optional
   * @type {string}
   * @memberof V1Port
   */
  name?: string;
  /**
   * Number of port to expose for the virtual machine. This must be a valid port number, 0 < x < 65536.
   * @type {number}
   * @memberof V1Port
   */
  port: number;
  /**
   * Protocol for port. Must be UDP or TCP. Defaults to \"TCP\". +optional
   * @type {string}
   * @memberof V1Port
   */
  protocol?: string;
}
