// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1NodeSelectorTerm } from './V1NodeSelectorTerm';

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it\'s a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 * @export
 * @interface V1PreferredSchedulingTerm
 */
export interface V1PreferredSchedulingTerm {
  /**
   *
   * @type {V1NodeSelectorTerm}
   * @memberof V1PreferredSchedulingTerm
   */
  preference: V1NodeSelectorTerm;
  /**
   * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
   * @type {number}
   * @memberof V1PreferredSchedulingTerm
   */
  weight: number;
}
