// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1HTTPGetAction } from './V1HTTPGetAction';
import { V1TCPSocketAction } from './V1TCPSocketAction';

/**
 * Probe describes a health check to be performed against a VirtualMachineInstance to determine whether it is alive or ready to receive traffic.
 * @export
 * @interface V1Probe
 */
export interface V1Probe {
  /**
   * Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1. +optional
   * @type {number}
   * @memberof V1Probe
   */
  failureThreshold?: number;
  /**
   *
   * @type {V1HTTPGetAction}
   * @memberof V1Probe
   */
  httpGet?: V1HTTPGetAction;
  /**
   * Number of seconds after the VirtualMachineInstance has started before liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes +optional
   * @type {number}
   * @memberof V1Probe
   */
  initialDelaySeconds?: number;
  /**
   * How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1. +optional
   * @type {number}
   * @memberof V1Probe
   */
  periodSeconds?: number;
  /**
   * Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness. Minimum value is 1. +optional
   * @type {number}
   * @memberof V1Probe
   */
  successThreshold?: number;
  /**
   *
   * @type {V1TCPSocketAction}
   * @memberof V1Probe
   */
  tcpSocket?: V1TCPSocketAction;
  /**
   * Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes +optional
   * @type {number}
   * @memberof V1Probe
   */
  timeoutSeconds?: number;
}
