// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * TCPSocketAction describes an action based on opening a socket
 * @export
 * @interface V1TCPSocketAction
 */
export interface V1TCPSocketAction {
  /**
   * Optional: Host name to connect to, defaults to the pod IP.
   * @type {string}
   * @memberof V1TCPSocketAction
   */
  host?: string;
}
