// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1HPETTimer } from './V1HPETTimer';
import { V1HypervTimer } from './V1HypervTimer';
import { V1KVMTimer } from './V1KVMTimer';
import { V1PITTimer } from './V1PITTimer';
import { V1RTCTimer } from './V1RTCTimer';

/**
 * Represents all available timers in a vmi.
 * @export
 * @interface V1Timer
 */
export interface V1Timer {
  /**
   *
   * @type {V1HPETTimer}
   * @memberof V1Timer
   */
  hpet?: V1HPETTimer;
  /**
   *
   * @type {V1HypervTimer}
   * @memberof V1Timer
   */
  hyperv?: V1HypervTimer;
  /**
   *
   * @type {V1KVMTimer}
   * @memberof V1Timer
   */
  kvm?: V1KVMTimer;
  /**
   *
   * @type {V1PITTimer}
   * @memberof V1Timer
   */
  pit?: V1PITTimer;
  /**
   *
   * @type {V1RTCTimer}
   * @memberof V1Timer
   */
  rtc?: V1RTCTimer;
}
