// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1VirtualMachineInstanceNetworkInterface
 */
export interface V1VirtualMachineInstanceNetworkInterface {
  /**
   * The interface name inside the Virtual Machine
   * @type {string}
   * @memberof V1VirtualMachineInstanceNetworkInterface
   */
  interfaceName?: string;
  /**
   * IP address of a Virtual Machine interface
   * @type {string}
   * @memberof V1VirtualMachineInstanceNetworkInterface
   */
  ipAddress?: string;
  /**
   * List of all IP addresses of a Virtual Machine interface
   * @type {Array<string>}
   * @memberof V1VirtualMachineInstanceNetworkInterface
   */
  ipAddresses?: string[];
  /**
   * Hardware address of a Virtual Machine interface
   * @type {string}
   * @memberof V1VirtualMachineInstanceNetworkInterface
   */
  mac?: string;
  /**
   * Name of the interface, corresponds to name of the network assigned to the interface
   * @type {string}
   * @memberof V1VirtualMachineInstanceNetworkInterface
   */
  name?: string;
}
