// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ListMeta } from './V1ListMeta';
import { V1VirtualMachineInstanceMigration } from './V1VirtualMachineInstanceMigration';

/**
 * VirtualMachineInstanceMigrationList is a list of VirtualMachineMigrations
 * @export
 * @interface V1VirtualMachineInstanceMigrationList
 */
export interface V1VirtualMachineInstanceMigrationList {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationList
   */
  apiVersion?: string;
  /**
   *
   * @type {Array<V1VirtualMachineInstanceMigration>}
   * @memberof V1VirtualMachineInstanceMigrationList
   */
  items: V1VirtualMachineInstanceMigration[];
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationList
   */
  kind?: string;
  /**
   *
   * @type {V1ListMeta}
   * @memberof V1VirtualMachineInstanceMigrationList
   */
  metadata?: V1ListMeta;
}
