// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VirtualMachineInstanceTemplateSpec } from './V1VirtualMachineInstanceTemplateSpec';
import { V1alpha1DataVolume } from './V1alpha1DataVolume';

/**
 * VirtualMachineSpec describes how the proper VirtualMachine should look like
 * @export
 * @interface V1VirtualMachineSpec
 */
export interface V1VirtualMachineSpec {
  /**
   * dataVolumeTemplates is a list of dataVolumes that the VirtualMachineInstance template can reference. DataVolumes in this list are dynamically created for the VirtualMachine and are tied to the VirtualMachine\'s life-cycle.
   * @type {Array<V1alpha1DataVolume>}
   * @memberof V1VirtualMachineSpec
   */
  dataVolumeTemplates?: V1alpha1DataVolume[];
  /**
   *
   * @type {object}
   * @memberof V1VirtualMachineSpec
   */
  runStrategy?: object;
  /**
   * Running controls whether the associatied VirtualMachineInstance is created or not Mutually exclusive with RunStrategy
   * @type {boolean}
   * @memberof V1VirtualMachineSpec
   */
  running?: boolean;
  /**
   *
   * @type {V1VirtualMachineInstanceTemplateSpec}
   * @memberof V1VirtualMachineSpec
   */
  template: V1VirtualMachineInstanceTemplateSpec;
}
