// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ObjectMeta } from './V1ObjectMeta';
import { V1VirtualMachineSpec } from './V1VirtualMachineSpec';
import { V1VirtualMachineStatus } from './V1VirtualMachineStatus';

/**
 * VirtualMachine handles the VirtualMachines that are not running or are in a stopped state The VirtualMachine contains the template to create the VirtualMachineInstance. It also mirrors the running state of the created VirtualMachineInstance in its status.
 * @export
 * @interface V1VirtualMachine
 */
export interface V1VirtualMachine {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @type {string}
   * @memberof V1VirtualMachine
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1VirtualMachine
   */
  kind?: string;
  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1VirtualMachine
   */
  metadata?: V1ObjectMeta;
  /**
   *
   * @type {V1VirtualMachineSpec}
   * @memberof V1VirtualMachine
   */
  spec?: V1VirtualMachineSpec;
  /**
   *
   * @type {V1VirtualMachineStatus}
   * @memberof V1VirtualMachine
   */
  status?: V1VirtualMachineStatus;
}
