// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1VirtualMachineInstanceCondition
 */
export interface V1VirtualMachineInstanceCondition {
  /**
   *
   * @type {string}
   * @memberof V1VirtualMachineInstanceCondition
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof V1VirtualMachineInstanceCondition
   */
  reason?: string;
  /**
   *
   * @type {string}
   * @memberof V1VirtualMachineInstanceCondition
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof V1VirtualMachineInstanceCondition
   */
  type: string;
}
