// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VirtualMachineCondition } from './V1VirtualMachineCondition';
import { V1VirtualMachineStateChangeRequest } from './V1VirtualMachineStateChangeRequest';

/**
 * VirtualMachineStatus represents the status returned by the controller to describe how the VirtualMachine is doing
 * @export
 * @interface V1VirtualMachineStatus
 */
export interface V1VirtualMachineStatus {
  /**
   * Hold the state information of the VirtualMachine and its VirtualMachineInstance
   * @type {Array<V1VirtualMachineCondition>}
   * @memberof V1VirtualMachineStatus
   */
  conditions?: V1VirtualMachineCondition[];
  /**
   * Created indicates if the virtual machine is created in the cluster
   * @type {boolean}
   * @memberof V1VirtualMachineStatus
   */
  created?: boolean;
  /**
   * Ready indicates if the virtual machine is running and ready
   * @type {boolean}
   * @memberof V1VirtualMachineStatus
   */
  ready?: boolean;
  /**
   * StateChangeRequests indicates a list of actions that should be taken on a VMI e.g. stop a specific VMI then start a new one.
   * @type {Array<V1VirtualMachineStateChangeRequest>}
   * @memberof V1VirtualMachineStatus
   */
  stateChangeRequests?: V1VirtualMachineStateChangeRequest[];
}
