// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ObjectMeta } from './V1ObjectMeta';
import { V1VirtualMachineInstanceMigrationSpec } from './V1VirtualMachineInstanceMigrationSpec';
import { V1VirtualMachineInstanceMigrationStatus } from './V1VirtualMachineInstanceMigrationStatus';

/**
 * VirtualMachineInstanceMigration represents the object tracking a VMI\'s migration to another host in the cluster
 * @export
 * @interface V1VirtualMachineInstanceMigration
 */
export interface V1VirtualMachineInstanceMigration {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigration
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigration
   */
  kind?: string;
  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1VirtualMachineInstanceMigration
   */
  metadata?: V1ObjectMeta;
  /**
   *
   * @type {V1VirtualMachineInstanceMigrationSpec}
   * @memberof V1VirtualMachineInstanceMigration
   */
  spec?: V1VirtualMachineInstanceMigrationSpec;
  /**
   *
   * @type {V1VirtualMachineInstanceMigrationStatus}
   * @memberof V1VirtualMachineInstanceMigration
   */
  status?: V1VirtualMachineInstanceMigrationStatus;
}
