// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VirtualMachineInstanceMigrationCondition } from './V1VirtualMachineInstanceMigrationCondition';

/**
 * VirtualMachineInstanceMigration reprents information pertaining to a VMI\'s migration.
 * @export
 * @interface V1VirtualMachineInstanceMigrationStatus
 */
export interface V1VirtualMachineInstanceMigrationStatus {
  /**
   *
   * @type {Array<V1VirtualMachineInstanceMigrationCondition>}
   * @memberof V1VirtualMachineInstanceMigrationStatus
   */
  conditions?: V1VirtualMachineInstanceMigrationCondition[];
  /**
   *
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationStatus
   */
  phase?: string;
}
