// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1DomainSpec } from './V1DomainSpec';
import { V1LabelSelector } from './V1LabelSelector';

/**
 *
 * @export
 * @interface V1VirtualMachineInstancePresetSpec
 */
export interface V1VirtualMachineInstancePresetSpec {
  /**
   *
   * @type {V1DomainSpec}
   * @memberof V1VirtualMachineInstancePresetSpec
   */
  domain?: V1DomainSpec;
  /**
   *
   * @type {V1LabelSelector}
   * @memberof V1VirtualMachineInstancePresetSpec
   */
  selector: V1LabelSelector;
}
