// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VirtualMachineInstanceCondition } from './V1VirtualMachineInstanceCondition';
import { V1VirtualMachineInstanceMigrationState } from './V1VirtualMachineInstanceMigrationState';
import { V1VirtualMachineInstanceNetworkInterface } from './V1VirtualMachineInstanceNetworkInterface';

/**
 * VirtualMachineInstanceStatus represents information about the status of a VirtualMachineInstance. Status may trail the actual state of a system.
 * @export
 * @interface V1VirtualMachineInstanceStatus
 */
export interface V1VirtualMachineInstanceStatus {
  /**
   * Conditions are specific points in VirtualMachineInstance\'s pod runtime.
   * @type {Array<V1VirtualMachineInstanceCondition>}
   * @memberof V1VirtualMachineInstanceStatus
   */
  conditions?: V1VirtualMachineInstanceCondition[];
  /**
   * Interfaces represent the details of available network interfaces.
   * @type {Array<V1VirtualMachineInstanceNetworkInterface>}
   * @memberof V1VirtualMachineInstanceStatus
   */
  interfaces?: V1VirtualMachineInstanceNetworkInterface[];
  /**
   * Represents the method using which the vmi can be migrated: live migration or block migration
   * @type {string}
   * @memberof V1VirtualMachineInstanceStatus
   */
  migrationMethod?: string;
  /**
   *
   * @type {V1VirtualMachineInstanceMigrationState}
   * @memberof V1VirtualMachineInstanceStatus
   */
  migrationState?: V1VirtualMachineInstanceMigrationState;
  /**
   * NodeName is the name where the VirtualMachineInstance is currently running.
   * @type {string}
   * @memberof V1VirtualMachineInstanceStatus
   */
  nodeName?: string;
  /**
   * Phase is the status of the VirtualMachineInstance in kubernetes world. It is not the VirtualMachineInstance status, but partially correlates to it.
   * @type {string}
   * @memberof V1VirtualMachineInstanceStatus
   */
  phase?: string;
  /**
   *
   * @type {object}
   * @memberof V1VirtualMachineInstanceStatus
   */
  qosClass?: object;
  /**
   * A brief CamelCase message indicating details about why the VMI is in this state. e.g. \'NodeUnresponsive\' +optional
   * @type {string}
   * @memberof V1VirtualMachineInstanceStatus
   */
  reason?: string;
}
