// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1LabelSelector } from './V1LabelSelector';
import { V1VirtualMachineInstanceTemplateSpec } from './V1VirtualMachineInstanceTemplateSpec';

/**
 *
 * @export
 * @interface V1VirtualMachineInstanceReplicaSetSpec
 */
export interface V1VirtualMachineInstanceReplicaSetSpec {
  /**
   * Indicates that the replica set is paused. +optional
   * @type {boolean}
   * @memberof V1VirtualMachineInstanceReplicaSetSpec
   */
  paused?: boolean;
  /**
   * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1. +optional
   * @type {number}
   * @memberof V1VirtualMachineInstanceReplicaSetSpec
   */
  replicas?: number;
  /**
   *
   * @type {V1LabelSelector}
   * @memberof V1VirtualMachineInstanceReplicaSetSpec
   */
  selector: V1LabelSelector;
  /**
   *
   * @type {V1VirtualMachineInstanceTemplateSpec}
   * @memberof V1VirtualMachineInstanceReplicaSetSpec
   */
  template: V1VirtualMachineInstanceTemplateSpec;
}
