// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ObjectMeta } from './V1ObjectMeta';
import { V1VirtualMachineInstanceReplicaSetSpec } from './V1VirtualMachineInstanceReplicaSetSpec';
import { V1VirtualMachineInstanceReplicaSetStatus } from './V1VirtualMachineInstanceReplicaSetStatus';

/**
 * VirtualMachineInstance is *the* VirtualMachineInstance Definition. It represents a virtual machine in the runtime environment of kubernetes.
 * @export
 * @interface V1VirtualMachineInstanceReplicaSet
 */
export interface V1VirtualMachineInstanceReplicaSet {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @type {string}
   * @memberof V1VirtualMachineInstanceReplicaSet
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1VirtualMachineInstanceReplicaSet
   */
  kind?: string;
  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1VirtualMachineInstanceReplicaSet
   */
  metadata?: V1ObjectMeta;
  /**
   *
   * @type {V1VirtualMachineInstanceReplicaSetSpec}
   * @memberof V1VirtualMachineInstanceReplicaSet
   */
  spec?: V1VirtualMachineInstanceReplicaSetSpec;
  /**
   *
   * @type {V1VirtualMachineInstanceReplicaSetStatus}
   * @memberof V1VirtualMachineInstanceReplicaSet
   */
  status?: V1VirtualMachineInstanceReplicaSetStatus;
}
