// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1VirtualMachineInstanceMigrationState
 */
export interface V1VirtualMachineInstanceMigrationState {
  /**
   * Indicates that the migration has been requested to abort
   * @type {boolean}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  abortRequested?: boolean;
  /**
   * Indicates the final status of the live migration abortion
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  abortStatus?: string;
  /**
   * Indicates the migration completed
   * @type {boolean}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  completed?: boolean;
  /**
   * The time the migration action ended
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  endTimestamp?: string;
  /**
   * Indicates that the migration failed
   * @type {boolean}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  failed?: boolean;
  /**
   * The VirtualMachineInstanceMigration object associated with this migration
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  migrationUid?: string;
  /**
   * The source node that the VMI originated on
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  sourceNode?: string;
  /**
   * The time the migration action began
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  startTimestamp?: string;
  /**
   * The list of ports opened for live migration on the destination node
   * @type {object}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  targetDirectMigrationNodePorts?: object;
  /**
   * The target node that the VMI is moving to
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  targetNode?: string;
  /**
   * The address of the target node to use for the migration
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  targetNodeAddress?: string;
  /**
   * The Target Node has seen the Domain Start Event
   * @type {boolean}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  targetNodeDomainDetected?: boolean;
  /**
   * The target pod that the VMI is moving to
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationState
   */
  targetPod?: string;
}
