// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1WatchEvent
 */
export interface V1WatchEvent {
  /**
   *
   * @type {string}
   * @memberof V1WatchEvent
   */
  object: string;
  /**
   *
   * @type {string}
   * @memberof V1WatchEvent
   */
  type: string;
}
