// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1I6300ESBWatchdog } from './V1I6300ESBWatchdog';

/**
 * Named watchdog device.
 * @export
 * @interface V1Watchdog
 */
export interface V1Watchdog {
  /**
   *
   * @type {V1I6300ESBWatchdog}
   * @memberof V1Watchdog
   */
  i6300esb?: V1I6300ESBWatchdog;
  /**
   * Name of the watchdog.
   * @type {string}
   * @memberof V1Watchdog
   */
  name: string;
}
