// tslint:disable
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PodAffinityTerm } from './V1PodAffinityTerm';

/**
 * The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
 * @export
 * @interface V1WeightedPodAffinityTerm
 */
export interface V1WeightedPodAffinityTerm {
  /**
   *
   * @type {V1PodAffinityTerm}
   * @memberof V1WeightedPodAffinityTerm
   */
  podAffinityTerm: V1PodAffinityTerm;
  /**
   * weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
   * @type {number}
   * @memberof V1WeightedPodAffinityTerm
   */
  weight: number;
}
