export const DASH = '-';

export enum StatusType {
  New = 'New',
  Pending = 'Pending',
  ContainerCreating = 'ContainerCreating',
  InProgress = 'In Progress',
  Running = 'Running',
  Updating = 'Updating',
  Upgrading = 'Upgrading',
  Cancelled = 'Cancelled',
  Expired = 'Expired',
  NotReady = 'Not Ready',
  Terminating = 'Terminating',
  Warning = 'Warning',
  ContainerCannotRun = 'ContainerCannotRun',
  CrashLoopBackOff = 'CrashLoopBackOff',
  Critical = 'Critical',
  Error = 'Error',
  Failed = 'Failed',
  InstallCheckFailed = 'InstallCheckFailed',
  Lost = 'Lost',
  Rejected = 'Rejected',
  Accepted = 'Accepted',
  Active = 'Active',
  Bound = 'Bound',
  Complete = 'Complete',
  Completed = 'Completed',
  Enabled = 'Enabled',
  Succeeded = 'Succeeded',
  Ready = 'Ready',
  Uptodate = 'Up to date',
  Info = 'Info',
  Unknown = 'Unknown',
}
